### ISSUE TITLE
视差范围设置

### ISSUE THREAD

**Issue by CloseSensor** [rebecca0011/UAVStereo#6]
作者您好，我想请问用基于Cost Volume的CNN来训练时，视差范围应当如何设置？有无参考范围？我在论文中的实验部分没有看到这一点

**Comment by rebecca0011** [comment]
> 作者您好，我想请问用基于Cost Volume的CNN来训练时，视差范围应当如何设置？有无参考范围？我在论文中的实验部分没有看到这一点

视差范围可以根据数据集的视差分布确定，视差分布一般与影像分辨率相关很大。本数据集在960*540的分辨率影像上设置为384px

**Comment by CloseSensor** [comment]
噢好的，谢谢您
